name: "Bug"
description: Report an unexpected problem or unintended behavior.
type: 'Bug'
body:
  - type: textarea
    id: Details
    attributes:
      label: Details
      description: "Describe the problem and reproduction steps."
