name: "Epic"
description: Outline a large body of work or project that is broken down.
type: 'epic'
body:
  - type: textarea
    id: Summary
    attributes:
      label: Summary
      description: "Brief summary of the scope of this epic."
  - type: textarea
    id: Resources
    attributes:
      label: Resources
      description: "Outline the timeline and staffing plan."
